name: Publish pull request content on netlify

on:
  workflow_run:
    workflows:
      - 'Build website on pull request'
    types:
      - completed

jobs:
  publish:
    name: Publish content of the website pull request on netlify
    runs-on: ubuntu-22.04
    steps:
      - name: Download website content artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: website-content
          path: content

      - name: Set PR_NUMBER and PR_SHA variables
        id: vars
        run: |
          echo "PR_NUMBER=$(<content/PR_NUMBER)" > /tmp/> $GITHUB_OUTPUT
          echo "PR_SHA=$(<content/PR_SHA)" >> $GITHUB_OUTPUT
      - name: 'Update status of Pull Request'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo: { owner, repo } } = context;
            const netlifyUrl = 'http://dummy-link';
            const fs = require('node:fs');
            const sha = fs.promises.readFile('content/PR_SHA');
            console.log('length is' + sha.length);
            // ensure it's a valid sha and contains only hex characters (no space, dot, etc) else exit
            if (sha && !sha.match(/^[0-9a-fA-F]+$/)) {
              throw new Error('Invalid PR_SHA');
            }

            await github.rest.repos.createCommitStatus({ owner, repo, sha, state: "success", target_url: netlifyUrl, description: "See pull request website online", context: "netlify"})          
